title: "Создание Docker и CI/CD конфигурации"
category: "create"
subcategory: "devops"
difficulty: "intermediate"
description: |
  Этот промпт помогает создать полную конфигурацию Docker и CI/CD для проекта,
  включая Dockerfile, docker-compose.yml и CI/CD пайплайны для различных окружений,
  с учетом всех требований безопасности, тестирования и развертывания.

example: |
  Пожалуйста, создайте Docker и CI/CD конфигурацию со следующими требованиями:

  1. Dockerfile:
     - Многоэтапная сборка
     - Оптимизация размера образа
     - Безопасная конфигурация
     - Кэширование слоев
     - Переменные окружения
     - Здоровье-чек
     - Непривилегированный пользователь
     - Минимальный базовый образ
     - Очистка кэша и временных файлов
  
  2. docker-compose.yml:
     - Сервисы (frontend, backend, db, cache)
     - Сети и тома
     - Переменные окружения
     - Зависимости между сервисами
     - Масштабирование
     - Логирование
     - Мониторинг
     - Резервное копирование
  
  3. CI/CD пайплайны:
     - GitHub Actions или GitLab CI
     - Этапы:
       - Линтинг и форматирование
       - Тестирование (unit, integration, e2e)
       - Сборка Docker-образов
       - Сканирование безопасности
       - Деплой в разные окружения
     - Кэширование
     - Артефакты
     - Уведомления
     - Автоматическое версионирование
  
  4. Безопасность:
     - Сканирование уязвимостей
     - Проверка зависимостей
     - Секреты и переменные
     - Безопасные базовые образы
     - Аудит контейнеров
     - Сетевая изоляция
  
  5. Мониторинг и логирование:
     - Prometheus метрики
     - Grafana дашборды
     - ELK стек
     - Трейсинг
     - Алерты
     - Логирование в stdout/stderr
  
  6. Оптимизация:
     - Кэширование слоев Docker
     - Параллельное выполнение тестов
     - Оптимизация размера образов
     - Минимизация времени сборки
     - Эффективное использование ресурсов

expected_outcome: |
  Ассистент создаст:
  1. Оптимизированный Dockerfile с многоэтапной сборкой
  2. Полный docker-compose.yml с настройкой всех сервисов
  3. CI/CD пайплайны для разных окружений
  4. Конфигурацию мониторинга и логирования
  5. Скрипты для автоматизации
  6. Документацию по развертыванию
  7. Инструкции по безопасности
  8. Конфигурацию бэкапов

notes: |
  При создании Docker и CI/CD конфигурации следует учитывать:
  - Использовать официальные базовые образы
  - Следовать принципам безопасности
  - Оптимизировать размер образов
  - Настроить правильное кэширование
  - Обеспечить изоляцию сервисов
  - Настроить мониторинг и логирование
  - Использовать секреты для чувствительных данных
  - Настроить автоматическое масштабирование
  - Обеспечить отказоустойчивость